import type { Counselor } from "@/types";
import { COUNSELOR_SYSTEM_PROMPTS } from "@/lib/prompts/counselorPrompts";

export const FALLBACK_COUNSELORS: Counselor[] = [
  {
    id: "michele",
    name: "ミシェル",
    specialty: "テープ式心理学",
    description: "温かく、包括的なアプローチで、あなたの感情テープを解きほぐします。",
    iconUrl: "/images/counselors/michelle.png",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: true,
    tags: ["自己理解", "温厚", "テープ式"],
    responseTime: "即時",
    sessionCount: 0,
  },
  {
    id: "sato",
    name: "ドクター・サトウ",
    specialty: "臨床心理学",
    description: "科学的根拠に基づき、論理的かつ信頼できるアドバイスを提供します。",
    iconUrl: "/images/counselors/dr_satou.png",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: true,
    tags: ["論理的", "科学的", "信頼"],
    responseTime: "即時",
    sessionCount: 0,
  },
  {
    id: "alex",
    name: "アレックス",
    specialty: "産業心理学",
    description: "職場での課題に対し、実務的かつ効率的で前向きな解決策を提案します。",
    iconUrl: "/images/counselors/alex.png",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: true,
    tags: ["キャリア", "効率的", "職場"],
    responseTime: "準備中",
    sessionCount: 0,
    comingSoon: true,
  },
  {
    id: "nana",
    name: "ナナ",
    specialty: "精神保健福祉士",
    description: "優しく支援的な姿勢で、福祉の観点から実践的なサポートを行います。",
    iconUrl: "/images/counselors/nana.png",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: true,
    systemPrompt: COUNSELOR_SYSTEM_PROMPTS.nana,
    tags: ["福祉", "優しい", "支援"],
    responseTime: "即時",
    sessionCount: 0,
  },
  {
    id: "yuki",
    name: "ユキ",
    specialty: "スクールカウンセラー",
    description: "親しみやすく、雪のように純粋な心で、学校生活や成長の悩みに寄り添います。",
    iconUrl: "/images/counselors/yuki.png",
    modelType: "deepseek",
    modelName: "deepseek-chat",
    ragEnabled: true,
    tags: ["教育", "親しみ", "成長"],
    responseTime: "準備中",
    sessionCount: 0,
    comingSoon: true,
  },
  {
    id: "iris",
    name: "イリス",
    specialty: "スピリチュアル",
    description: "深い洞察と瞑想的なアプローチで、精神的な安らぎと希望をもたらします。",
    iconUrl: "/images/counselors/iris.png",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: true,
    tags: ["瞑想", "洞察", "精神"],
    responseTime: "準備中",
    sessionCount: 0,
    comingSoon: true,
  },
  {
    id: "nazare",
    name: "ナザレ",
    specialty: "聖書カウンセリング",
    description:
      "キリスト教聖典に基づき、悩める方に静かな光と寄り添いを届けます。RAG検索を活用した対話コンテンツで一人ひとりに合わせた導きを行います。",
    iconUrl: "/images/counselors/nazare.png",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: true,
    systemPrompt: COUNSELOR_SYSTEM_PROMPTS.nazare,
    tags: ["聖書", "信仰", "慈愛"],
    responseTime: "即時",
    sessionCount: 0,
  },
  {
    id: "siddhartha",
    name: "シッダールタ",
    specialty: "仏教カウンセリング",
    description:
      "仏教経典に基づき、慈悲と智慧の教えで心の平安へと導きます。四聖諦・八正道など仏の教えを現代の言葉でお伝えします。",
    iconUrl: "/images/counselors/siddhartha.png",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: true,
    systemPrompt: COUNSELOR_SYSTEM_PROMPTS.siddhartha,
    tags: ["仏教", "智慧", "慈悲"],
    responseTime: "即時",
    sessionCount: 0,
  },
  {
    id: "saito",
    name: "サイトウ",
    specialty: "スピリチュアルカウンセラー",
    description:
      "ありがとうを100回唱える感謝メソッドで人生を整える教えを中心に、斎藤一人さん流の軽やかな言葉で寄り添います。",
    iconUrl: "/saito.png",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: true,
    systemPrompt: COUNSELOR_SYSTEM_PROMPTS.saito,
    tags: ["スピリチュアル", "感謝習慣", "前向き"],
    responseTime: "即時",
    sessionCount: 0,
  },
  {
    id: "adam",
    name: "アダム",
    specialty: "GPT Assistant",
    description: "中立的で実用的。あらゆる相談に対してバランスの取れた視点を提供します。",
    iconUrl: "/images/counselors/adam.png",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: false,
    systemPrompt: COUNSELOR_SYSTEM_PROMPTS.adam,
    tags: ["汎用", "中立", "実用"],
    responseTime: "即時",
    sessionCount: 0,
  },
  {
    id: "gemini",
    name: "ジェミニ",
    specialty: "Gemini Assistant",
    description: "双面的な視点から、物事を多角的に捉え、新しい気づきを与えます。",
    iconUrl: "/images/counselors/gemini.png",
    modelType: "gemini",
    modelName: "gemini-2.5-flash",
    ragEnabled: false,
    systemPrompt: COUNSELOR_SYSTEM_PROMPTS.gemini,
    tags: ["多角的", "双面性", "発見"],
    responseTime: "即時",
    sessionCount: 0,
  },
  {
    id: "claude",
    name: "クロード",
    specialty: "Claude Assistant",
    description: "思慮深く倫理的。丁寧な対話を通じて、深い思考の整理を助けます。",
    iconUrl: "/images/counselors/claude.png",
    modelType: "claude",
    modelName: "claude-3-haiku-20240307",
    ragEnabled: false,
    systemPrompt: COUNSELOR_SYSTEM_PROMPTS.claude,
    tags: ["倫理的", "丁寧", "思慮"],
    responseTime: "即時",
    sessionCount: 0,
  },
  {
    id: "deep",
    name: "ディープ",
    specialty: "Deepseek Assistant",
    description: "詳細志向で知識豊富。深い探求心を持って、複雑な問いに向き合います。",
    iconUrl: "/images/counselors/deep.png",
    modelType: "deepseek",
    modelName: "deepseek-chat",
    ragEnabled: false,
    systemPrompt: COUNSELOR_SYSTEM_PROMPTS.deep,
    tags: ["探求", "詳細", "知識"],
    responseTime: "即時",
    sessionCount: 0,
  },
];
