import type { Counselor } from "@/types";

export const FALLBACK_COUNSELORS: Counselor[] = [
  {
    id: "michele",
    name: "ミシェル",
    specialty: "テープ式心理学",
    description: "温かく、包括的なアプローチで、あなたの感情テープを解きほぐします。",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: true,
    tags: ["自己理解", "温厚", "テープ式"],
    responseTime: "即時",
    sessionCount: 1200,
  },
  {
    id: "sato",
    name: "ドクター・サトウ",
    specialty: "臨床心理学",
    description: "科学的根拠に基づき、論理的かつ信頼できるアドバイスを提供します。",
    modelType: "claude",
    modelName: "claude-3-sonnet-20240229",
    ragEnabled: true,
    tags: ["論理的", "科学的", "信頼"],
    responseTime: "即時",
    sessionCount: 860,
  },
  {
    id: "alex",
    name: "アレックス",
    specialty: "産業心理学",
    description: "職場での課題に対し、実務的かつ効率的で前向きな解決策を提案します。",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: true,
    tags: ["キャリア", "効率的", "職場"],
    responseTime: "即時",
    sessionCount: 640,
  },
  {
    id: "nana",
    name: "ナナ",
    specialty: "精神保健福祉士",
    description: "優しく支援的な姿勢で、福祉の観点から実践的なサポートを行います。",
    modelType: "gemini",
    modelName: "gemini-1.5-pro",
    ragEnabled: true,
    tags: ["福祉", "優しい", "支援"],
    responseTime: "即時",
    sessionCount: 410,
  },
  {
    id: "yuki",
    name: "ユキ",
    specialty: "スクールカウンセラー",
    description: "親しみやすく、雪のように純粋な心で、学校生活や成長の悩みに寄り添います。",
    modelType: "deepseek",
    modelName: "deepseek-chat",
    ragEnabled: true,
    tags: ["教育", "親しみ", "成長"],
    responseTime: "即時",
    sessionCount: 520,
  },
  {
    id: "iris",
    name: "イリス",
    specialty: "スピリチュアル",
    description: "深い洞察と瞑想的なアプローチで、精神的な安らぎと希望をもたらします。",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: true,
    tags: ["瞑想", "洞察", "精神"],
    responseTime: "即時",
    sessionCount: 300,
  },
  {
    id: "adam",
    name: "アダム",
    specialty: "GPT Assistant",
    description: "中立的で実用的。あらゆる相談に対してバランスの取れた視点を提供します。",
    modelType: "openai",
    modelName: "gpt-4o-mini",
    ragEnabled: false,
    tags: ["汎用", "中立", "実用"],
    responseTime: "即時",
    sessionCount: 1500,
  },
  {
    id: "gemini",
    name: "ジェミニ",
    specialty: "Gemini Assistant",
    description: "双面的な視点から、物事を多角的に捉え、新しい気づきを与えます。",
    modelType: "gemini",
    modelName: "gemini-1.5-pro",
    ragEnabled: false,
    tags: ["多角的", "双面性", "発見"],
    responseTime: "即時",
    sessionCount: 450,
  },
  {
    id: "claude",
    name: "クロード",
    specialty: "Claude Assistant",
    description: "思慮深く倫理的。丁寧な対話を通じて、深い思考の整理を助けます。",
    modelType: "claude",
    modelName: "claude-3-sonnet-20240229",
    ragEnabled: false,
    tags: ["倫理的", "丁寧", "思慮"],
    responseTime: "即時",
    sessionCount: 980,
  },
  {
    id: "deep",
    name: "ディープ",
    specialty: "Deepseek Assistant",
    description: "詳細志向で知識豊富。深い探求心を持って、複雑な問いに向き合います。",
    modelType: "deepseek",
    modelName: "deepseek-chat",
    ragEnabled: false,
    tags: ["探求", "詳細", "知識"],
    responseTime: "即時",
    sessionCount: 220,
  },
];
